version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: deckdrop-postgres
    environment:
      POSTGRES_USER: deckdrop
      POSTGRES_PASSWORD: deckdrop
      POSTGRES_DB: deckdrop
    ports:
      - '5432:5432'
    volumes:
      - deckdrop_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: deckdrop-redis
    ports:
      - '6379:6379'

volumes:
  deckdrop_postgres_data:
